export enum SuitState {
  RETIRADO = 'RETIRADO',
  ENLOCALLMPIO = 'ENLOCALLIMPIO',
  LAVANDERIALUCECITASUCIO = 'LAVANDERIALUCECITASUCIO',
  LAVANDERIALUCECITALIMPIO = 'LAVANDERIALUCECITALIMPIO',
  LAVANDERIACELIASUCIO = 'LAVANDERIACELIASUCIO',
  LAVANDERIACELIALIMPIO = 'LAVANDERIACELIALIMPIO',
  LAVANDERIACENTROSUCIO = 'LAVANDERIACENTROSUCIO',
  LAVANDERIACENTROLIMPIO = 'LAVANDERIACENTROLIMPIO',
  MODISTA = 'MODISTA',
  ENLOCALSUCIO = 'ENLOCALSUCIO',
  LISTOENTREGA = 'LISTOENTREGA',
}
export enum SuitCategory {
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
  E = 'E',
}
